version: "3.2"

services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: vrn
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql:
